### ISSUE TITLE
Altitude wallet password issue

### ISSUE THREAD

**Issue by elpolako12** [TheLindaProjectInc/Altitude#12]
Hi, i have recently tried to do transaction from my altitude wallet i am asked for password which i have not setup. I have done in past transactions and never been asked for password is there any way to fix this issue??

**Comment by davidstoneham** [comment]
Altitude should not ask for a password unless your wallet is encrypted or it is unsure on the encryption status. Restarting Altitude should solve the problem. Also, make sure you are not running Lindad separately in case you are using an older version that does not communicate the wallet.dat encryption status to Altitude. 

If you continue to have an issue please jump into or discord (https://discord.gg/SHNjQBv) and support will be happy to help you out
