### ISSUE TITLE
Crash in macOS 

### ISSUE THREAD

**Issue by CHAiNS77** [TheLindaProjectInc/Altitude#19]
Release from Jan 27 crashes. 
[Crash_Altitude .pdf](https://github.com/TheLindaProjectInc/Altitude/files/4125727/Crash_Altitude.pdf)
Reverted to previous release.

**Comment by davidstoneham** [comment]
A new build has been added for the 2.1.4 release that resolves this issue. Just re-download the 2.1.4 release and you should be good to go
