### ISSUE TITLE
Wallet Won't Load

### ISSUE THREAD

**Issue by jc40204** [TheLindaProjectInc/Altitude#245]
Description of issue: Please describe the issue with as much information as possible.

Metrix Core Comm Error
Problem communicating asks me to check debug.log file for issues. 

Please advise steps need to restore communication. 

Machine: x64 win32
Altitude: 3.2.0
Metrix Core: 
Connections: 0
Blocks: 0
Log: 400:Bad Request

**Comment by SeqSEE** [comment]
Hey @jc40204, were you able to check in the debug log for more information?

Without knowing what the debug log says it's hard to pinpoint your exact issue. Fastest way to get back on tract would probably be to update Metrix core from within Altitude and  afterwards use the bootstrap to sync faster.

**Comment by jc40204** [comment]
Thanks for your reply. I updated everything and had to bootstrap twice to
get the connections back.

Back to normal now. Thanks for your help.

Thank you,


John C. Bennett
