### ISSUE TITLE
The altitude wallet is syncing up till block 681821. All peers are then lost with no further updates. I have uninstall are reinstall, but to no avail.

### ISSUE THREAD

**Issue by Beeman35** [TheLindaProjectInc/Altitude#249]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.2.0
Metrix Core: 4.0.9.1
Connections: 1
Blocks: 681821
Log: https://file.io/fUxrqTngXhwN

**Comment by SeqSEE** [comment]
@Beeman35 can you try updating Metrix core from within Altitude? After it updates, you should be able to use the bootstrap option to get synced up faster.

**Comment by Beeman35** [comment]
Thanks for your direction. I've tried the updating with no results, but the bootstrapping did it. It's working now.
