### ISSUE TITLE
passphrase

### ISSUE THREAD

**Issue by memmo77** [TheLindaProjectInc/Altitude#25]
How can I recover my passphrase? By mistake I didn't save it

Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 2.1.5
Metrix Core: v3.4.6.0-g
Connections: 25
Blocks: 104238
Log: https://file.io/LfJEBWvxmCq6

**Comment by davidstoneham** [comment]
Hi, unfortunately it is not possible to recover your passphrase. The wallet file is encrypted using the passphrase and can only be unencrypted with that passphrase. There are tools available that can attempt to crack your passphrase if you have an idea of what it is (i.e. not sure if it had capitals or some numbers) but these tools come with no guarantee of success

**Comment by anywalletrecovery** [comment]
@memmo77 
I have powerful machine to retrieve lost passphrase of wallet. for fast response text me in telegram or gmail
Telegram: @walletrecover
anywalletrecovery@gmail.com
