### ISSUE TITLE
Mrx tokens sent missing from my wallet 

### ISSUE THREAD

**Issue by Fgjam** [TheLindaProjectInc/Altitude#27]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 darwin
Altitude: 2.1.5
Metrix Core: v3.4.7.0-g
Connections: 31
Blocks: 237329
Log: [object Object]

Hi,

I sent 500,000 MRX coins to my Altitude and they are not showing as received. My wallet is still at 0 coins.

Date
Asset
Amount
Fee
Net Amount
To Address
Transaction ID
Status
2020-08-02 15:06:10MRX500,000.001000000.00100000500,000.00000000LYhCiDPG9eYMA1yVnYYYfUjC9sADzac9Qfaab7b84a1c66d230c00d33a14a47082dce6f956c6c1978df3d88545f1e5975e4Complete

MRX
Asset Name	Metrix
Date Requested	2020-08-02 15:06:10
Status	Complete
Status Date	2020-08-02 15:10:09
Amount	500,000.00100000
Fee	0.00100000
Net Amount	500,000.00000000
Address	
Transaction ID	
Deposit MRX
Withdraw MRX
Go To Market

**Comment by Fgjam** [comment]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 darwin
Altitude: 2.1.5
Metrix Core: v3.4.7.0-g
Connections: 31
Blocks: 237329
Log: [object Object]

Hi,

I sent 500,000 MRX coins to my Altitude and they are not showing as received. My wallet is still at 0 coins.

Date
Asset
Amount
Fee
Net Amount
To Address
Transaction ID
Status
2020-08-02 15:06:10MRX500,000.001000000.00100000500,000.00000000LYhCiDPG9eYMA1yVnYYYfUjC9sADzac9Qfaab7b84a1c66d230c00d33a14a47082dce6f956c6c1978df3d88545f1e5975e4Complete

MRX
Asset Name	Metrix
Date Requested	2020-08-02 15:06:10
Status	Complete
Status Date	2020-08-02 15:10:09
Amount	500,000.00100000
Fee	0.00100000
Net Amount	500,000.00000000
Address
Transaction ID
Deposit MRX
Withdraw MRX
Go To Market

**Comment by blackout00000** [comment]
Hello,

This is likely due to the blockchain not being fully synchronized on your computer. Please also ensure that the receiving address you supplied matches the current altitude address. For further technical support, please join us on our discord channel and we would be happy to assist.
