### ISSUE TITLE
Haven't received Tokens

### ISSUE THREAD

**Issue by thaggs** [TheLindaProjectInc/Altitude#28]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 2.1.5
Metrix Core: v3.4.7.0-g
Connections: 7
Blocks: 1147516
Log: https://file.io/D98j2E1hc5Ap
I have not received these tokens yet: What can I do??

Asset:	Metrix
Requested Amount:	1434989.00100000 MRX
Withdraw Fee:	0.00100000 MRX
Receiving Amount:	1434989.00000000 MRX
Receiving Address:	LYV9EEzG4nJ6L41wKyWcNXudVQDQyz5Wiq

Thanks,

Greg

**Comment by thaggs** [comment]
Awesome issues resolved. Tokens arrived and r stacked. Thank you.

**Comment by davidstoneham** [comment]
@thaggs glad it's all sorted!
