### ISSUE TITLE
Visually identify addresses which are not P2PK or P2PKH

### ISSUE THREAD

**Issue by SeqSEE** [TheLindaProjectInc/Altitude#335]
It is possible to have multiple types of Metrix address in the wallet, however only "normal" P2PK and P2PKH addresses can be used for things like staking and contract interactions. With no clear way to differentiate them, outside of inspection of the base58check prefix, a user may be confused about them.

Adding some sort of additional visual identifications specifying `segwit` and `p2sh-segwit` addresses which can also exist in a user's wallet would help them to identify these addresses.

**Comment by SeqSEE** [comment]
I think this issue should still be open. It would be a good thing for users to be able to distinguish the addresses they are using.

**Comment by nibbles83** [comment]
https://github.com/TheLindaProjectInc/Altitude/releases/tag/3.4.0 release to address this
