### ISSUE TITLE
Dwa dni temu otworzyłem portfel i do dziś mam 0 confirmations.Znikneły monety.

### ISSUE THREAD

**Issue by szafir2** [TheLindaProjectInc/Altitude#37]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.1
Metrix Core: 4.0.1.0
Connections: 10
Blocks: 28757
Log: https://file.io/j21IebDARfFP

**Comment by davidstoneham** [comment]
Hi, You wallet just needs to sync the blockchain. If you are still having issues please head to our discord https://discord.com/invite/5nwrTwJ

Cześć, Twój portfel musi tylko zsynchronizować łańcuch bloków. Jeśli nadal masz problemy, przejdź do naszej niezgody
