### ISSUE TITLE
Wallet crashed and will not restart 

### ISSUE THREAD

**Issue by SpeedKingZR1** [TheLindaProjectInc/Altitude#385]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.1.0
Metrix Core: 4.1.1.0
Connections: 1
Blocks: 0
Log: https://file.io/uALHHZ6fkmMI

I've tried restarting altitude and the resync got to 87% and stopped. I restarted the program and deleted the local chain files but nothing works

**Comment by SeqSEE** [comment]
Hey @SpeedKingZR1 it seems like you may have a outdated version of of Altitude. Do you still have the issue when you are using the most up to date version of the wallet?

https://github.com/TheLindaProjectInc/Altitude/releases/tag/3.2.1

**Comment by SpeedKingZR1** [comment]
Hello, The issue was resolved, a member on discord spent a few hours with me on Saturday and we identified the issue of the outdated wallet and a few other things via the debug logs. Thank you Vatche Najarian On May 13, 2023, at 6:27 PM, Sarah ***@***.***> wrote:﻿
Hey @SpeedKingZR1 it seems like you may have a outdated version of of Altitude. Do you still have the issue when you are using the most up to date version of the wallet?
https://github.com/TheLindaProjectInc/Altitude/releases/tag/3.2.1
