### ISSUE TITLE
Improve "time to next stake" value

### ISSUE THREAD

**Issue by brmmm3** [TheLindaProjectInc/Altitude#41]
The "Time to next stake" value makes no sense with the current implementation. As you can see in the screenshot
![Screenshot_20201114_091528](https://user-images.githubusercontent.com/21258241/99142951-ffc55780-2659-11eb-885a-f43bb5f18fa8.jpg) (left axis shows time to next stake in seconds, right axis shows number of coins staking) the "Time to next stake" has not correlation with the time when the next stake will be received.

**Comment by davidstoneham** [comment]
Time to next stake isn't a predictable number. It was originally implemented as a very rough indicator when POS was first created. It is simply a value that shows your weight (coins x age) in the staking lottery vs the past winners of the last 24 hours.
Being a lottery based on hashes of numbers there is no way to predict when your next stake will be with any sort of accuracy.

**Comment by nibbles83** [comment]
Closing this no fix possible.
