### ISSUE TITLE
Altitude App No Longer Updating Blocks

### ISSUE THREAD

**Issue by Iamzeus84** [TheLindaProjectInc/Altitude#48]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.8
Metrix Core: 4.0.4.0
Connections: 7
Blocks: 137903
Log: https://file.io/AN7KuEvsiFOP

**Comment by nibbles83** [comment]
Most block update issues can be resolved by updating to the latest version and bootstrapping.
I would advise coming to the discord to get further assistance.
https://discord.gg/ZFqJu4c
