### ISSUE TITLE
Expetced Return

### ISSUE THREAD

**Issue by D4nbiker** [TheLindaProjectInc/Altitude#509]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.3.2
Metrix Core: 4.2.0.1
Connections: 10
Blocks: 1300671
Log: https://file.io/56uxdRS0jtA8

good morning,
my wallet is currently staking for 2÷3 days, the expetced return is always blocked on 7 hours by i didn't receive any reward. Is this a nromal condition? is any action necessary on my part? thank you very much

**Comment by nibbles83** [comment]
This is normal, the expected time is only a rough guide and will fluctuate as the network weight changes with every block.
I encourage you to join the discord if you wish to discuss anything Metrix related, we have representatives active 24/7 (https://discord.gg/kKk7ADAKDJ). You could of course deposit it into the tipbot to receive regular rewards as part of a pool.
