### ISSUE TITLE
scusate non ricordo piu la password del wallett di mrx ...? come posso recuperare

### ISSUE THREAD

**Issue by peppe1388** [TheLindaProjectInc/Altitude#51]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.9
Metrix Core: 4.0.3.0
Connections: 10
Blocks: 170210
Log: https://file.io/2F2HlSVraY4h

**Comment by nibbles83** [comment]
Encryption passwords cannot be recovered. Just keep trying possible passwords and password combinations.
