### ISSUE TITLE
Vanished account

### ISSUE THREAD

**Issue by MelvinAsbaqi** [TheLindaProjectInc/Altitude#52]
I updated my wallet and my account has vanished now

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nibbles83** [comment]
Is your wallet fully in sync?
What version did you upgrade from?

I would advise coming to the discord to get immediate assistance.
https://discord.gg/ZFqJu4c

**Comment by MelvinAsbaqi** [comment]
No it’s not. It shows that I received amount in transaction history but It is not in my wallet. I don’t know it updated automatically Sent from Mail for Windows 10 From: nibbles83Sent: Tuesday, March 23, 2021 4:14 PMTo: TheLindaProjectInc/AltitudeCc: MelvinAsbaqi; AuthorSubject: Re: [TheLindaProjectInc/Altitude] Vanished account (#52) Is your wallet fully in sync?What version did you upgrade from?I would advise coming to the discord to get immediate assistance.https://discord.gg/ZFqJu4c—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by nibbles83** [comment]
Click the tools > repair > bootstrap button. That will get you back in sync.
Then Recover Transactions 1, if your balance is missing.

**Comment by nibbles83** [comment]
Try repair > rescan.
If that doesnt work then please come to the discord where we can assist in realtime.

**Comment by nibbles83** [comment]
I would advise coming to the discord if you still require assistance.
https://discord.gg/ZFqJu4c
