### ISSUE TITLE
Warning! You are not on the main chain according to the Metrix explorer. It is highly recommended to re-sync or re-bootstrap your blockchain to avoid the loss of any coins.

### ISSUE THREAD

**Issue by crshovrd41** [TheLindaProjectInc/Altitude#53]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 darwin
Altitude: 2.1.5
Metrix Core: v3.4.6.0-g
Connections: 5
Blocks: 685998
Log: [object Object]

Hello, getting the warning in the subject line. Ran bootstrap and re-sync. No change. What should I try next?
![Screen Shot 2021-03-23 at 3 35 50 PM](https://user-images.githubusercontent.com/35728378/112227822-7b797700-8bed-11eb-9d55-a7db9832b9a1.png)

**Comment by nibbles83** [comment]
You are on a very old wallet and I'm assuming you also missed the chain swap last year.

**Comment by crshovrd41** [comment]
> You are on a very old wallet and I'm assuming you also missed the chain swap last year.

Cool, so, should I just upgrade the wallet? I'm pretty sure I just updated but I will try again

**Comment by ckhatton** [comment]
v2 of the wallet was before the coin swap and thus a different type of coin. If you didn't carry out the swap of the coins, then I am afraid it is too late.

**Comment by crshovrd41** [comment]
> v2 of the wallet was before the coin swap and thus a different type of coin. If you didn't carry out the swap of the coins, then I am afraid it is too late.

Gotcha. So, delete everything and go cry in a corner?

**Comment by ckhatton** [comment]
I'm not going to say to go and actively delete everything, but if the coins you are after are in that wallet version (thus you haven't carried out the swap procedure, which is now closed) and they are not sitting on MyNodePool or an exchange, then I'm afraid there's not much else you can do.
