### ISSUE TITLE
Metrix Altitude Wallet Missing Coins

### ISSUE THREAD

**Issue by ciremartin** [TheLindaProjectInc/Altitude#54]
Description of issue: I had close to 2 million MRX in my Altitude wallet. I did the swap back in November or December 2020 and all of my coins transferred properly. I've had multiple transactions come up that are for 937,421 and 937,447 and 940,152 MRX for a payment. Somehow I reinstalled the wallet I think and they came back but then the same thing keeps happening everytime I fix it. The last transaction says Orphan next to it and the coin count is 946,389.45651452 on February 28, 2021 at 9:15am. Can this be fixed and can I get my coins back? 

Machine: x64 win32
Altitude: 3.0.10
Metrix Core: 4.0.6.0
Connections: 10
Blocks: 182865
Log: https://file.io/Pe4vYcvfoAUC

**Comment by nibbles83** [comment]
Yes.
Click the Tools > Repair > Bootstrap button.
Once thats completed, then click the Tools > Repair > Recover Transactions 2 button.
Thanks should get you fixed.
If that doesn't work, please join our Discord server for further assistance.
https://discord.gg/SHNjQBv

**Comment by Hich8952** [comment]
I have the same issue. Lost all coins about 3.5M

**Comment by Hich8952** [comment]
Initialising Metrix Core...

**Comment by Hich8952** [comment]
How do I add a .dat file to the new wallet?

**Comment by nibbles83** [comment]
I would advise coming to the discord if you still require assistance.
https://discord.gg/ZFqJu4c
