### ISSUE TITLE
An unknown error has occured.

### ISSUE THREAD

**Issue by AndyMS583** [TheLindaProjectInc/Altitude#56]
Description of issue: Every some Seconds get the error:
An unknown error has occured. You may need to restart your wallet and try again. If problems persist please contact support.

Try to fix so much things - but nothing worked for me.

Machine: x64 win32
Altitude: 3.0.10
Metrix Core: 4.0.6.0
Connections: 10
Blocks: 200486
Log: https://file.io/fB3yjXk7uLBV

**Comment by nibbles83** [comment]
Hi Andy, if you leave the wallet open to sync it will fix itsself. 
Following the chain fork at 200k there are a bunch of forks so the wallet is just sorting out the correct one.

If your still getting these messages after a couple of hours drop by the discord and we can take a deeper look at it.
