### ISSUE TITLE
Lost 85K in MRX after wallet deposit.

### ISSUE THREAD

**Issue by JuiceKrewe** [TheLindaProjectInc/Altitude#59]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.11
Metrix Core: 4.0.6.1
Connections: 7
Blocks: 199433
Log: https://file.io/QKDEKhwcy9qK

**Comment by nibbles83** [comment]
You need to bootstrap the wallet from the tools repair menu. Your blocks are behind on sync

**Comment by JuiceKrewe** [comment]
I just did this, and nothing changed. As previously stated they were in the wallet before shutdown the computer.

**Comment by nibbles83** [comment]
Come to the discord, we have a support team that can help.

**Comment by JuiceKrewe** [comment]
Sure in on discord, what's the info?

**Comment by nibbles83** [comment]
All sorted on discord I believe. 👍
