### ISSUE TITLE
"Non-arrival of crypto in the wallet"

### ISSUE THREAD

**Issue by Mister290977** [TheLindaProjectInc/Altitude#597]
"Good morning, I'm having an issue receiving MRX crypto. I sent MRX from Bitmart to my wallet. I copied and pasted the address perfectly. Bitmart shows that the transaction was sent, but the funds haven't appeared in my wallet yet. Could I get some information on this? Thank you."

**Comment by SeqSEE** [comment]
The best way to see information about a withdraw where you only have the txid would be on the blockchain explorer which can be found at https://explorer.metrixcoin.com

Hope this helps

**Comment by nibbles83** [comment]
Please join the Discord if this is still an issue. Its likely that the wallet needs bootstrapping or that the wallet is not fully in sync.

**Comment by Mister290977** [comment]
Hi, unfortunately, the crypto hasn't arrived in my Altitude wallet yet. I
followed your instructions, but they haven't come through. Can you help me
resolve the issue? Thanks.

Il giorno mar 24 set 2024 alle ore 17:20 nibbles83 ***@***.***>
ha scritto:

**Comment by SeqSEE** [comment]
@Mister290977 if you join the MetrixCoin discord we can more easily help you diagnose your specific issue. 

https://discord.gg/5Mj67juv5J
