### ISSUE TITLE
Governatore

### ISSUE THREAD

**Issue by giallu7** [TheLindaProjectInc/Altitude#60]
I have a problem. I can't become governor. When I request registration, the 7.5M coin + fees (18.05) transaction is not confirmed; hours and days go by but always zero confirmations. You can help me?
the portfolio is synchronized and updated to the latest versions.
Tnks

Machine: x64 win32
Altitude: 3.0.11
Metrix Core: 4.0.6.2
Connections: 10
Blocks: 212383
Log: https://file.io/OR0EX0iDqXCd

**Comment by nibbles83** [comment]
I believe this is a fee issue. Ensure the governor coins reside on the same address you stake from. That will ensure that there are enough fees to cover the enrollment.
Any further issues log a ticket in the discord.
