### ISSUE TITLE
Metrix Core Communication Error

### ISSUE THREAD

**Issue by nunjachomp** [TheLindaProjectInc/Altitude#602]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.4.0
Metrix Core: 
Connections: 0
Blocks: 0

Log: https://file.io/xLnnBcgW72OO
[text.txt](https://github.com/user-attachments/files/16662761/text.txt)

There was a problem communicating with Metrix Core. It is recommended to check your debug.log file for issues.

**Comment by nibbles83** [comment]
Please join the Discord if this is still an issue. Its likely that the wallet needs bootstrapping or that the daemon has not correctly downloaded.
