### ISSUE TITLE
There is an error that Metrix wallet will not start

### ISSUE THREAD

**Issue by fatefuldebt** [TheLindaProjectInc/Altitude#608]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by nibbles83** [comment]
Please join the Discord if this is still an issue. Its likely that the wallet needs bootstrapping or that the daemon has not correctly downloaded.
