### ISSUE TITLE
Error message metrix core

### ISSUE THREAD

**Issue by bbenjo** [TheLindaProjectInc/Altitude#61]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.11
Metrix Core: 4.0.6.1
Connections: 9
Blocks: 13258
Log: https://file.io/kepoT5dmYl05

Every time I open altitude wallet i have an error message from the metrix core. 

I did a back up of my wallet, uninstall the wall, re install the wallet and i still have an error message. 

How do i put my .dat file in the altitude wallet? I think i lost all my coins

Thank you

**Comment by nibbles83** [comment]
Please come to the discord and log a support ticket. If you completed the swap last December then we will get you fixed.
