### ISSUE TITLE
problemi con il wallet altitude

### ISSUE THREAD

**Issue by ziojack1976** [TheLindaProjectInc/Altitude#65]
Buona sera , ho effettuato nell'arco di due mesi acquisti per circa 691000 MRX .da un paio di settimane , il wallet altitude mi segnala 0 MRX ma su explorer c'e' tutto!!! e' possibile risolvere il problema ? vorrei acquistarne ancora ma non so se fidarmi!!! Grazie !!!

Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.11
Metrix Core: 4.0.6.2
Connections: 10
Blocks: 37410
Log: https://file.io/EbTBT1wJeFH1

**Comment by nibbles83** [comment]
Please raise a ticket in our Discord. We have a support team available to assist.
https://discord.gg/ZFqJu4c
