### ISSUE TITLE
White screen Ticket-2518 log

### ISSUE THREAD

**Issue by smartinks** [TheLindaProjectInc/Altitude#69]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.13
Metrix Core: 4.0.6.2
Connections: 10
Blocks: 233948
Log: https://file.io/knrVW2iKulU7

**Comment by nibbles83** [comment]
I see you have raised a discord ticket for this. Will close this issue on here and continue with the ticket.
