### ISSUE TITLE
stacking impossible

### ISSUE THREAD

**Issue by Greg2323** [TheLindaProjectInc/Altitude#72]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.13
Metrix Core: 4.0.6.2
Connections: undefined
Blocks: 240962
Log: https://file.io/cF2YGjQWHYga

**Comment by nibbles83** [comment]
Please raise a ticket in our Discord. We have a support team available to assist.
https://discord.gg/ZFqJu4c
