### ISSUE TITLE
issue 

### ISSUE THREAD

**Issue by szafir2** [TheLindaProjectInc/Altitude#73]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.13
Metrix Core: 4.0.6.2
Connections: 0
Blocks: 264990
Log: https://file.io/AYwhc0t78DXa

**Comment by nibbles83** [comment]
You appear to be stuck on a fork. Please use the tools > repair > bootstrap button to get back in sync.
If issues continue , please raise a ticket in our Discord.
https://discord.gg/ZFqJu4c
