### ISSUE TITLE
Have not received my coins yet.

### ISSUE THREAD

**Issue by AnthonyV81** [TheLindaProjectInc/Altitude#74]
Description of issue: I have made two transfers so far to the altitude wallet from my coin base account using bitcoin but still have not received the coins in my wallet on altitude. The history shows both transitions from being sent and received but still shows zero balance on my coins. 

Machine: x64 win32
Altitude: 3.0.13
Metrix Core: 4.0.6.2
Connections: 9
Blocks: 265576
Log: https://file.io/oQL9jeP664q2

**Comment by nibbles83** [comment]
Looks like your wallet is stuck on a fork.
Click the tools > repair > bootstrap to fix it.

**Comment by AnthonyV81** [comment]
I just went through those steps how long after should I see results of the coins appearing in the wallet? 
   
   
   
    On 06/29/2021 11:48 AM nibbles83 ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Looks like your wallet is stuck on a fork.Click the tools > repair > bootstrap to fix it.

**Comment by nibbles83** [comment]
Almost immediately, if not then click the recover transactions button in th repair menu.

**Comment by AnthonyV81** [comment]
yeah I tried both steps a few times and still nothing showed up in my wallet
   
   
   
    On 06/29/2021 12:44 PM nibbles83 ***@***.***> wrote:
    
   
     
    
   
     
    
     
   Almost immediately, if not then click the recover transactions button in th repair menu.

**Comment by nibbles83** [comment]
If your still having issues with this i would suggest raising a support ticket in our discord and one of the support team will help to get things going.
https://discord.gg/ZFqJu4c

Thanks

**Comment by AnthonyV81** [comment]
sounds good thank you
   
   
   
    On 07/01/2021 1:52 AM nibbles83 ***@***.***> wrote:
    
   
     
    
   
     
    
     
   If your still having issues with this i would suggest raising a support ticket in our discord and one of the support team will help to get things going.https://discord.gg/ZFqJu4c 
   Thanks
