### ISSUE TITLE
Metrix Core Wallet doesn't give correct info, and doen't stake anymore

### ISSUE THREAD

**Issue by floepie1** [TheLindaProjectInc/Altitude#76]
Description of issue: Please describe the issue with as much information as possible

Hi, my Metrix Core Wallet doesn't give me any staking rewards anymore.
It keeps hanging, 
My Wallet is atking, but input = 0, expected return = 0
Transactions stay immature
and my Balance is not correct. I started with about 30 M and have only 7 M left ??
My spending Balance dropped to 0
and my pending balance to 7M, but that cannot be correct

Machine: x64 win32
Altitude: 3.0.13
Metrix Core: 4.0.6.2
Connections: 8
Blocks: 265110
Log: https://file.io/2IVbo7jrFKbH

![afbeelding](https://user-images.githubusercontent.com/72673771/124569419-38fb4380-de46-11eb-9515-e8dafc5c9888.png)

![afbeelding](https://user-images.githubusercontent.com/72673771/124570208-f2f2af80-de46-11eb-87c8-72e93e343744.png)

![afbeelding](https://user-images.githubusercontent.com/72673771/124570294-0a319d00-de47-11eb-9c36-40fa6cddd90e.png)

**Comment by nibbles83** [comment]
Hi,
Your wallet appears to have gotten stuck on a fork.
Please click "tools > repair > bootstrap" to get it syncing again.
Once its fully in sync you can use "tools > repair > recover transactions 1" to rescan the wallet for missing transactions/balance.
Thanks

**Comment by floepie1** [comment]
yep, that did it. THANK YOU so much for your swift and helpfull reply.

coulkd you also give som explanation about these negative transactions : payments to and orphan transactions I have no clue what it means.

![afbeelding](https://user-images.githubusercontent.com/72673771/124582803-a614d600-de52-11eb-893a-8d0a2d9d2eaa.png)

**Comment by nibbles83** [comment]
Those will have been recorded as orphan transactions.
Its possible they can be sometimes be cleaned from the wallet with "tools >repair >recover transactions 2"

**Comment by floepie1** [comment]
OK. TX.
