### ISSUE TITLE
I've been staking for over 2 weeks and I haven't received any coins. Is there something I'm supposed to do to retrieve them? thank you

### ISSUE THREAD

**Issue by JGibbons75** [TheLindaProjectInc/Altitude#83]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 darwin
Altitude: 3.0.14
Metrix Core: 4.0.7.0
Connections: 10
Blocks: 324598
Log: 400:Bad Request

**Comment by nibbles83** [comment]
I would advise logging a ticket in the Discord for assistance with sending/receiving & staking coins. We have a support team that can assist you in real time there.

https://discord.gg/sFDhZk4Nxb
