### ISSUE TITLE
I did not receive my deposit in the amount of 100000 MRX. Transaction ID - MA5PCg5CinVYZjCHPBapHFNdrLKwLj7yAN

### ISSUE THREAD

**Issue by Little-Ricky-Ham** [TheLindaProjectInc/Altitude#86]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.14
Metrix Core: 4.0.6.2
Connections: 9
Blocks: 264694
Log: https://file.io/WIFhTZUbwNX4

**Comment by nibbles83** [comment]
Duplicate issue.

**Comment by Funkydog-nl** [comment]
Also update your wallet please, you are a version behind
