### ISSUE TITLE
problem with stacking wallet

### ISSUE THREAD

**Issue by zoharazr** [TheLindaProjectInc/Altitude#88]
Description of issue: Please describe the issue with as much information as possible
I get 4900 coins in stacking 
and all my coin in panning 
and my balance is 0

Machine: x64 win32
Altitude: 3.0.14
Metrix Core: 4.0.7.0
Connections: 10
Blocks: 379010
Log: https://file.io/h1GJf3RXaHnI

**Comment by SeqSEE** [comment]
It seems like your log file no longer exists. Is this still an issue for you?
