### ISSUE TITLE
Wallet unlock problem

### ISSUE THREAD

**Issue by holyfire7734** [TheLindaProjectInc/Altitude#89]
Description of issue: Please describe the issue with as much information as possible

Machine: x64 win32
Altitude: 3.0.14
Metrix Core: 4.0.7.0
Connections: 10
Blocks: 386099
Log: https://file.io/6PuXHJeZzFuA

I did a dumpprivykey and now my passphrase will not unlock my wallet, what should I do to unlock my funds?

**Comment by SeqSEE** [comment]
First off it seems like your log file is no longer exists. Dumping your private key(s) should not effect the passphrase.

Are you still having this issue?
