### ISSUE TITLE
portafoglio metrix

### ISSUE THREAD

**Issue by magnussen78** [TheLindaProjectInc/Altitude#90]
Description of issue: Please describe the issue with as much information as possible

buonasera,nel mio portagoglio di metrix non visualizzo le monete comprate. erano circa 7400000.
potete aiutarmi?
Grazie
Patrizio

Machine: x64 win32
Altitude: 3.0.14
Metrix Core: 4.0.7.0
Connections: 0
Blocks: 1062
Log: https://file.io/G8R7MLA84qZM

**Comment by magnussen78** [comment]
Account	Address	Amount	Fee	Category	Confirmations	Time	Transaction Hash	Block Hash
buonasera,nel mio portagoglio di metrix non visualizzo le monete comprate. erano circa 7400000.
potete aiutarmi?
Grazie
Patrizio

**Comment by Funkydog-nl** [comment]
First make sure your wallet is fully synced. (check left bottom of the wallet)
If the wallet is fully synchronized with the network, try following option:
Go to  Tools -> Wallet repair -> Recover transactions 1, looks like you received an orphan stake
